"""Add auth_provider and auth_provider_id columns

Revision ID: 791b3732410e
Revises: 352befb5d43a
Create Date: 2026-03-18 10:38:44.316169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791b3732410e'
down_revision: Union[str, Sequence[str], None] = '352befb5d43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('thread_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=False)
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True, server_default='supabase'))
    op.add_column('users', sa.Column('auth_provider_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['auth_provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'auth_provider_id')
    op.drop_column('users', 'auth_provider')
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_column('conversations', 'thread_id')
    # ### end Alembic commands ###
